"""empty message

Revision ID: 116460b6d275
Revises: 
Create Date: 2023-05-27 15:46:08.761088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116460b6d275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=80), nullable=False),
    sa.Column('city_name', sa.String(length=80), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('donations_orders', sa.Integer(), nullable=True),
    sa.Column('donations_orders_done', sa.Integer(), nullable=True),
    sa.Column('donations_orders_cancelled', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('birthdate', sa.String(length=10), nullable=True),
    sa.Column('blood_type', sa.String(length=3), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('qty_donations', sa.Integer(), nullable=True),
    sa.Column('date_last_donation', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('donation_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=80), nullable=False),
    sa.Column('blood_type', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('qty_bags', sa.Integer(), nullable=True),
    sa.Column('date_donation_order', sa.DateTime(), nullable=True),
    sa.Column('city_name', sa.String(length=80), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('hospital', sa.Integer(), nullable=False),
    sa.Column('requester', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['hospital'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['requester'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('donation_order')
    op.drop_table('user')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
